plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
  pep8:
    enabled: true
  pylint:
    enabled: true
    checks:
      missing-module-docstring:
        enabled: false
      missing-class-docstring:
        enabled: false
    missing-function-docstring:
        enabled: false
    global-statement:
        enabled: false
    invalid-name:
        enabled: false
    too-many-arguments:
        enabled: false
  radon:
    enabled: true
exclude_paths:
  - tests/**
  - docs/**
ratings:
  paths:
    - satella/**
checks:
  argument-count:
    config:
      threshold: 15
  method-complexity:
    config:
      threshold: 50
  method-count:
    config:
      threshold: 85
  file-lines:
    enabled: true
    config:
      threshold: 700
