name: build-satella
run-name: ${{ github.actor }}
on: [ push ]
jobs:
  prepare-system:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-python@4
      - name: Install everything
        run: pip install -e .[test,dev,extras]
        with:
          python-version: '${{ matrix.python-version }}'
          cache: 'pip'
    paths: ["dist/*"]
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.6", "3.7", "3.8", "pypy3.9", "pypy3.10", "3.9", "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-python@4
        with:
          python-version: '${{ matrix.python-version }}'
          cache: 'pip'
      - name: Test everything
        run: pytest -n 8 -vv --cov=satella
        with:
          python-version: '${{ matrix.python-version }}'
          cache: 'pip'
  build_package:
    runs-on: ubuntu-latest
    steps:
      name: Build package
      uses: python -m build .

  convert_and_upload_coverage:
    steps:
      - run: coverage xml
      - uses: caffco/code-climate-github-action@v1.0.0
        env:
          CC_TEST_REPORTER_ID: """
    paths:
      - '!*.MD'
